---
apiVersion: v1
kind: Service
metadata:
  name: hook0-frontend
  namespace: mace-hooks
spec:
  selector:
    app: hook0-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hook0-frontend
  namespace: mace-hooks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hook0-frontend
  template:
    metadata:
      labels:
        app: hook0-frontend
    spec:
      containers:
        - name: frontend
          image: hook0/hook0-frontend:latest
          env:
            - name: API_URL
              value: "https://hooks2.maceinnovation.com"
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
